name: Hasura Permission Diff with Metadelta
branding:
  icon: check-circle
  color: purple

description: |
  On PR, compute the difference between the proposed changes (new) and the
  present state (old).

author: InvariantClub

inputs:
  hasura_path:
    required: true
    default: hasura/metadata
    description: |
      Path to your Hasura `metadata` folder.
  github_token:
    required: false
    description: "Repository GITHUB_TOKEN or PAT (Personal Access Token)."
    default: ${{ github.token }}
  artifact_retention_days:
    required: false
    default: 5
    description: |
      Number of days to save the diff as an artifact for. Clicking the link
      after this period will not work; you can just trigger the action to be
      run again, though, and get a new link.

runs:
  using: "composite"
  steps:
    - name: "Checkout the PR as the 'new' source"
      uses: actions/checkout@v4
      with:
        path: ./new
        ref: ${{ github.event.pull_request.head.sha }}


    - name: "Checkout `main` as the 'old' source"
      uses: actions/checkout@v4
      with:
        path: ./old
        ref: main


    - name: "Run metadelta comparing old and new"
      id: metadelta
      env:
        INPUT_HASURA_PATH: ${{ inputs.hasura_path }}
      shell: bash
      run: |
        docker run -i \
          -v $PWD:/work \
          ghcr.io/invariantclub/metadelta-cli \
          diff \
          -o /work/old/$INPUT_HASURA_PATH \
          --oldLabel 'main' \
          -n /work/new/$INPUT_HASURA_PATH \
          --newLabel '${{ github.event.pull_request.head.label }} @ ${{ github.event.pull_request.head.sha }}' \
          --newLink '${{ github.event.pull_request.html_url }}' \
          >diff.json || true
        echo "anythingDifferent=$(test -s diff.json || echo 'true')" >> "$GITHUB_OUTPUT"


    - name: "Uploading the diff as an artifact"
      uses: actions/upload-artifact@v4
      id: artifact
      if:
        # Only run if we detected changes.
        ${{ steps.metadelta.outputs.anythingDifferent != 'true' }}
      with:
        name: metadelta-diff
        path: diff.json
        retention-days: ${{ inputs.artifact_retention_days }}


    - name: "Comment with Metadelta link"
      uses: peter-evans/create-or-update-comment@v4.0.0
      if:
        # Only run if we uploaded an artifact
        ${{ steps.artifact.outcome == 'success' }}
      with:
        token: ${{ inputs.github_token }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          [View the permission diff in Metadelta :eyes:](https://metadelta.invariant.club/explorer?githubArtifact=${{ steps.artifact.outputs.artifact-id }}/${{ github.repository_owner }}/${{ github.event.repository.name }})

          This is was triggered from GitHub Actions [run ${{ github.run_number }}](https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}/).

